<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Voyager\Voyager.csproj" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\src\Voyager.SourceGenerator\Voyager.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\TransitiveClassLibrary\TransitiveClassLibrary.csproj" />
		<ProjectReference Include="..\Voyager.FluentValidation\Voyager.FluentValidation.csproj" />
		<ProjectReference Include="..\Voyager.Validot\Voyager.Validot.csproj" />
	</ItemGroup>
</Project>
